### ISSUE TITLE
[test] django-extensions>=2.0.7 missing in requirement.txt

### ISSUE THREAD

**Issue by hispanico** [openwisp/django-ipam#46]
Following the install development steps I get this error:
~/django-ipam/tests# ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/Django-2.0.8-py3.6.egg/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/Django-2.0.8-py3.6.egg/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/usr/local/lib/python3.6/dist-packages/Django-2.0.8-py3.6.egg/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/dist-packages/Django-2.0.8-py3.6.egg/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/dist-packages/Django-2.0.8-py3.6.egg/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_extensions'

**Comment by nemesifier** [comment]
@hispanico use `pip install -r requirements-test.txt`. See: https://github.com/openwisp/django-ipam/blob/master/requirements-test.txt. @anurag-ks you should advise to do that also in the `Install Development Version` which should be named `Install for Development` or something similar.
